# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut源代码
        uses: actions/checkout@v2

      - name: 安装node.Js环境
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 安装依赖
        run: npm install
      - name: 编译
        run: npm run build
      - name: 压缩
        run: |
          echo cd ${{ github.workspace }}
          cd ${{ github.workspace }}
          echo ls
          ls
          echo zip -q -r dist.zip ./dist
          zip -q -r dist.zip ./dist
          ls

      - name: 发布Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist.zip
